### ISSUE TITLE
Request: ZF Grants platform source and issue tracking.

### ISSUE THREAD

**Issue by nathan-at-least** [ZcashFoundation/zfnd#15]
Hi. I'm super jazzed… yes, JAZZED! about the ZF Grants site!

I poked around a bit to see if the platform is open source. Is it? Can we transition it towards open source?

The first-order thing I want is just transparent issue tracking for it for bugs or feature requests. If it's proprietary, should we use this repo?

Second-order, I think open source could have nice longer term bigger picture pay-offs. [Over on the Zcash forum](https://forum.zcashcommunity.com/t/zcash-community-developed-forum-software/33051/7?u=nathan-at-least) I'm agitating for community-maintained integrations between the different Zcash community sites (forum, chat, ZF grants, etc…). It's a wacky fun light-hearted experimental idea, which is that the more tie-ins we have between these systems the more it might improve the communities interactions.

Even without that wacky idea, though, having ZF Grants be open source can allow a more explicit form of "process governance" for grants. Changes to the process could be explicitly coded up and discussion embodied in pull requests. Worthwhile to think about.

**Edit:** Yet a third thought is that open source would allow public scrutiny of security issues with the grant sites.

**Comment by sonyamann** [comment]
The site is indeed open source! https://github.com/grant-project/zcash-grant-system

**Comment by nathan-at-least** [comment]
Perfect! I'm completely satisfied.
