### ISSUE TITLE
Add website to repository description

### ISSUE THREAD

**Issue by RichardLitt** [ZcashFoundation/zfnd#20]
In this section:

![Screen Shot 2019-06-23 at 14 28 19](https://user-images.githubusercontent.com/910753/59976330-31500580-95c3-11e9-81ad-2361733c1c99.png)

There ought to be a link to zfnd.org.

**Comment by chumzee** [comment]
hi its me ruzebelt

**Comment by acityinohio** [comment]
I...can't believe it took this long to fix this. Sorry!

**Comment by RichardLitt** [comment]
Ç'est la vie. Don't worry about it. :)
