### ISSUE TITLE
Permanently retire zcashfoundation.github.io

### ISSUE THREAD

**Issue by RichardLitt** [ZcashFoundation/zfnd#31]
This website is still up. I think that it should be replaced with a page advertising a redirect to zfnd.org. What do you think?

**Comment by acityinohio** [comment]
Thanks for the heads up @RichardLitt — rather than do the redirect I unarchived then renamed the repo (which was still serving because of the GH Pages repo connection). AFAIK no one ever accessed the site through the github.io domain so I think there's little risk simply removing the hosting.

**Comment by RichardLitt** [comment]
That works, too. Sweet.
