### ISSUE TITLE
Operate or fund community operators of essential Zcash infrastructure.

### ISSUE THREAD

**Issue by sonyamann** [ZcashFoundation/zfnd#4]
Copied over from the old GitHub repo: https://github.com/ZcashFoundation/ZcashFoundation/issues/63

Authored by @nathan-at-least.

-----

Currently ZcashCo operates various kinds of Zcash infrastructure. Probably the most essential are seed nodes.

Ideally from my perspective ZcashCo would no operate any Zcash infrastructure in order to make Zcash resilient against the scenario of ZcashCo turning evil / imploding / being coerced, etc… The Foundation would be in a good position to define a set of "essential infrastructure" and then potentially fund its operation through grants.

IMO, the essential infrastructure includes:

* Seeder nodes, which help new nodes bootstrap into the network.
* Sufficient nodes to ensure the blockchain history is available to new nodes. (Ideally the network naturally provides this.)
* Hosting of zkSNARK parameters, which are necessary for using shielded transactions.
* Arguably: Nodes operating Tor hidden services and/or I2P equivalent, to enable IP address privacy.

Tangentially: I'm not clear if operating infrastructure or organizing and funding others to operate public infrastructure is within the mandate of the Foundation. Can we clarify this publicly?

------

Previous comments can be seen at the original link.

**Comment by acityinohio** [comment]
Closing this out for clean-up/not using GH Issues this way in the main repo anymore
