### ISSUE TITLE
[Grant Programs] Update Grant Process

### ISSUE THREAD

**Issue by sonyamann** [ZcashFoundation/zfnd#5]
Copied over from the old GitHub repo: https://github.com/ZcashFoundation/ZcashFoundation/issues/71

Authored by @acityinohio.

------

There have been many issues presented regarding the Grant program (feedback, improvements, etc) and I wanted to collect them here as a general "how can we improve grants?" issue. Summarizing them here:

1) Increase frequency of grants/streamline opportunities for applications ([#69](https://github.com/ZcashFoundation/ZcashFoundation/issues/69))
2) Continuation/lower-barrier grants ([#70](https://github.com/ZcashFoundation/ZcashFoundation/issues/70))
3) Community funding + matching ([#41](https://github.com/ZcashFoundation/ZcashFoundation/issues/41), [#55](https://github.com/ZcashFoundation/ZcashFoundation/issues/55))

I think we'll need to update the Grant program significantly, if not in 2018Q4, for the following cycle (which may be continuous/not in the normal two quarter cadence!).

**Comment by prastut** [comment]
@sonyamann @acityinohio I had some questions around grant ideas, had emailed them contact@zfnd.org. Just wanted to know whether you have received them. Thanks for your time!

**Comment by sonyamann** [comment]
Hi @prastut! Yep, I received your email. Sometimes it takes me a couple of days to get to our incoming inquiries, but I do try to respond to most of them on the same day they were received. My apologies for the wait — I promise that I will get back to you soon! Probably tonight.

**Comment by acityinohio** [comment]
Closing this out thanks to [ZF Grants](https://grants.zfnd.org/).
